#!/bin/bash

if [ -z "$PSPAWN_DIR" ]; then
    PSPAWN_DIR=$(dirname `realpath $0`)
fi

conf="$PSPAWN_DIR/pspawn_data/pspawn.conf"

if [ -e "$conf" ]; then
    source "$conf"
fi

MOUNTPOINT="$PSPAWN_DIR/pspawn_data"
ENCRYPTED_DIR="$PSPAWN_DIR/pspawn_encrypted_data"
SIGNATURES_FILE="$PSPAWN_DIR/pspawn_ecryptfs_signatures"

fail() {
    echo "$@" >&2
    exit 1
}

# we don't want anyone snooping around our activities, so we avoid logging sudo commands
subash() {
    wd=${PSPAWN_DIR}
    cd "$HOME"
    echo "set -e ; cd $wd ;" "$@" "< `tty`" | sudo /bin/bash
    cd "$wd"
}

set -e

is_mounted() {
    mountpoint -q "$MOUNTPOINT" && return 0
    return 1
}

check_setup() {
    test -e "$ENCRYPTED_DIR" || return 1
    test -e "$SIGNATURES_FILE" || return 1
}

mount_encrypted_dir() {
    if is_mounted; then
        echo Already mounted
        return 0
    fi

    check_setup || fail "No encrypted container available"

    data_sig=`sed '1q;d' "${SIGNATURES_FILE}"`
    fnek_sig=`sed '2q;d' "${SIGNATURES_FILE}"`

    test -e "$MOUNTPOINT" || mkdir -p "$MOUNTPOINT"

    #if ! subash keyctl show | grep -q "$data_sig" || ! subash keyctl show | grep -q "$fnek_sig"; then
        subash ecryptfs-add-passphrase --fnek
    #fi

    subash mount -t ecryptfs \
        -o verbose,ecryptfs_sig=$data_sig,ecryptfs_fnek_sig=$fnek_sig,ecryptfs_cipher=aes,ecryptfs_key_bytes=32,ecryptfs_unlink_sigs,no_sig_cache,ecryptfs_enable_filename_crypto=y,ecryptfs_passthrough=n \
         "$ENCRYPTED_DIR" "$MOUNTPOINT"
}

umount_encrypted_dir() {
    is_mounted || return 0

    "$PSPAWN_DIR/pspawn" stop || true
    subash fuser -mk "$MOUNTPOINT" || true
    subash umount -f "$MOUNTPOINT"
}

create_encrypted_dir() {
    check_setup && return 1
    test -e "$MOUNTPOINT" && fail Data directory already exists

    stty -echo; printf "Passphrase: " 1>&2; read PASSWORD; stty echo
    echo "$PASSWORD" | ecryptfs-add-passphrase --fnek | \
    perl -n -e'/\[([^]]+)\]/ && print "$1\n"' | tee "${SIGNATURES_FILE}~"
    mv -f "${SIGNATURES_FILE}~" "${SIGNATURES_FILE}"

    mkdir -p "$ENCRYPTED_DIR"
}

cmd="$1"
shift

set -e

case "$cmd" in
    create)
        create_encrypted_dir
        ;;
    mount)
        mount_encrypted_dir
        ;;
    umount)
        umount_encrypted_dir
        ;;
    start)
        mount_encrypted_dir || fail
        "$PSPAWN_DIR/pspawn" start "$@"
        ;;
    stop)
        "$PSPAWN_DIR/pspawn" stop "$@"
        umount_encrypted_dir
        ;;
    p)
        if is_mounted; then
            "$PSPAWN_DIR/pspawn" "$@"
        else
            mount_encrypted_dir || fail
            "$PSPAWN_DIR/pspawn" "$@"
            umount_encrypted_dir
        fi
        ;;
    x)
        if is_mounted; then
            "$PSPAWN_DIR/xspawn" "$@"
        else
            mount_encrypted_dir || fail
            trap umount_encrypted_dir EXIT
            "$PSPAWN_DIR/xspawn" "$@"
        fi
        ;;
    exec)
        mount_encrypted_dir || fail
        "$@"
        umount_encrypted_dir
        ;;
    *)
        fail "$cmd: illegal command"
        ;;
esac
