#!/bin/bash

conf="$(dirname `realpath $0`)/pspawn.conf"

if [ -e "$conf" ]; then
    source "$conf"
fi

if [ -z "$PSPAWN_DIR" ]; then
    PSPAWN_DIR=$(dirname `realpath $0`)
fi

conf="$PSPAWN_DIR/pspawn_data/pspawn.conf"

if [ -e "$conf" ]; then
    source "$conf"
fi

if [ -z "$PSPAWN_PRIVILEGED" ]; then
    PSPAWN_PRIVILEGED=n
fi

if [ -z "$PSPAWN_LXC_NAME" ]; then
    PSPAWN_LXC_NAME="pspawn-lxc"
fi

if [ -z "$PSPAWN_DIR" ]; then
    PSPAWN_DIR=$(dirname `realpath $0`)
fi

PSPAWN_LXC_DIR="$PSPAWN_DIR/pspawn_data/lxc"

fail() {
    echo "$@" >&2
    exit 1
}

# we don't want anyone snooping around our activities, so we avoid logging sudo commands
subash() {
    wd=${PSPAWN_DIR}
    cd "$HOME"
    if tty > /dev/null; then
        stdin=`tty`
    else
        stdin='/dev/null'
    fi
    echo "set -e ; cd $wd ;" "$@" "< $stdin" | sudo /bin/bash
    cd "$wd"
}

lxccmd() {
    cmd=$1
    shift
    if test "$PSPAWN_PRIVILEGED" = "y"; then
        subash lxc-"$cmd" -P "${PSPAWN_LXC_DIR}" "$@"
    else
        lxc-"$cmd" -P "${PSPAWN_LXC_DIR}" "$@"
    fi
    return $?
}

chrootcmd() {
    if test "$PSPAWN_PRIVILEGED" = "y"; then
        subash chroot "$ROOTFS" "$@"
    else
        chroot "$ROOTFS" "$@"
    fi
    return $?
}

execcmd() {
    pid=$(lxccmd info -n $PSPAWN_LXC_NAME -H|grep 'PID:'|tr -s ' '|cut -d' ' -f2)

    if [ "x$pid" = "x" ]; then
        fail "Container isn't running"
    fi

    if test "$PSPAWN_PRIVILEGED" = "y"; then
        subash nsenter -a -Z -t $pid "$@"
    else
        nsenter -a -Z -t $pid "$@"
    fi
    return $?
}

ROOTFS=${PSPAWN_LXC_DIR}/$PSPAWN_LXC_NAME/rootfs

PSPAWN_LXC_START_ARGS="-s lxc.rootfs.path=$ROOTFS"

test -z "$1" && fail command required

cmd=$1
shift

case "$cmd" in
    create)
        test -e "$PSPAWN_LXC_DIR" || mkdir -p "$PSPAWN_LXC_DIR"
        lxccmd create \
            -B dir \
            -n $PSPAWN_LXC_NAME \
            -t download \
            -- -d ubuntu -a amd64
        chrootcmd /usr/bin/passwd ubuntu
        ;;
    start)
        lxccmd "$cmd" \
            -n $PSPAWN_LXC_NAME \
            $PSPAWN_LXC_START_ARGS \
            $PSPAWN_LXC_START_ARGS_EXTRA \
            "$@"
        ;;
    execute)
        execcmd "$@"
        ;;
    enter)
        execcmd /bin/bash -l
        ;;
    conf)
        echo "$PSPAWN_LXC_DIR/$PSPAWN_LXC_NAME/config"
        ;;
    root)
        echo "$ROOTFS"
        ;;
    chroot)
        chrootcmd "$@"
        ;;
    ls)
        lxccmd ls "$@"
        ;;
    exec)
        lxccmd attach -n $PSPAWN_LXC_NAME "$@" || \
        lxccmd execute -n $PSPAWN_LXC_NAME "$@"
        ;;
    *)
        lxccmd $cmd -n $PSPAWN_LXC_NAME "$@"
        ;;
esac

exit $?
